### ISSUE TITLE
Define fixed table column properties at the workspace level

### ISSUE THREAD

**Issue by pvaut** [cggh/panoptes#10]
#### Current situation

The settings of a fixed table column (i.e. a column defined in the dataset) can only be modified at the level of the dataset, not at the level of a workspace.
#### Desired situation

For some settings (i.e. visibility), it would be desirable to be able to set them at the level of a workspace
#### Solution

Create a level of indirection by duplicating the record with column settings for each workspace.

**Comment by leehart** [comment]
Obsolete? Panoptes no longer has workspaces (since v2)?

**Comment by benjeffery** [comment]
Yep, no workspaces anymore.
