### ISSUE TITLE
State of template based pages

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#1109]
Currently there is no good way for a template derived component to alter it's representation in app state.
A solution would be for `HTMLWithComponents` to accept a prop that is an object that it recurses through along with the HTML, which assigns props to the HTML. `HTMLWithComponents` could then have a `setProps` method and pass `setProps` to descendants similar to how this is done in the genome browser with it's channels.

**Comment by leehart** [comment]
First things first: http://www.its-not-its.info/

**Comment by benjeffery** [comment]
Its not a problem though right?

**Comment by leehart** [comment]
No, the interpreter didn't fail. It just threw out a sarcastic warning. ;-)
