### ISSUE TITLE
Genome Browser: The gene visualisation (gene line and coding sequence blue block) disappear at a high zoom level.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#1140]
_From @leehart on August 1, 2018 10:14_

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Genes [channel]

_Copied from original issue: wtchg-kwiatkowski/observatory-web#179_

**Comment by benjeffery** [comment]
Fetching logic needs tweaking for cases where gene straddles fetch block. See https://github.com/cggh/panoptes/blob/master/webapp/src/js/components/panoptes/genome/tracks/AnnotationChannel.js#L107

**Comment by leehart** [comment]
Verification of fix:

No issue found in the example Genotypes dataset
New tab [tab] > Genome Browser [button] > [zoom in on Genes channel] > [see that the gene line and coding sequence blue blocks are still visible]
