### ISSUE TITLE
Config shouldn't fail if feed URL is not fetchable

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#1145]

**Comment by leehart** [comment]
To reproduce, change the URL in the feeds section of the dataset settings to something bogus, and see that the home page no longer loads, i.e. the page remains blank.
```
feeds:
  blog: https://analytics-cms.malariagenBUG.net/feed
```
The JavaScript console shows an `XMLHttpRequest` error (uncaught exception), and the webapp log seems to show a worker timeout error (maybe unrelated).

**Comment by leehart** [comment]
This particular test case is proving trickier to handle (it times out; it appears we can't catch the error on the server-side before the client-side throws an error)
```
blog: https://analytics-cms.malariagen.net:9999/feed
```

**Comment by benjeffery** [comment]
Set a tight timeout on ther server's request?
