### ISSUE TITLE
Evaluate preferred/primary database engine

### ISSUE THREAD

**Issue by alimanfoo** [cggh/panoptes#156]
Consider whether MySQL is the best engine.

**Comment by benjeffery** [comment]
Some work done with MonetDB - which I liked. I leave this here till we change/decide not to.

**Comment by benjeffery** [comment]
Note that we should consider future GIS needs...

**Comment by alimanfoo** [comment]
Just throwing this into the mix, worth also considering supporting sqlite?
I like the idea that I (or similar power user) might be able to do an
almost zero config deploy of panoptes on a local machine for my own
personal use and experimentation, if I didn't have to muck around with a db
server that would make life much easier.

I remember mentioning this to Paul a while back, he said Panoptes currently
depends on a number of mysql-specific features. So this may not be
feasible, but just wanted to raise it for discussion.

Maybe docker would be an alternative solution for zero-config deploy, if
mysql etc. already setup inside the image.

On Monday, July 4, 2016, Ben Jeffery <notifications@github.com> wrote:

> Note that we should consider future GIS needs...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cggh/panoptes/issues/156#issuecomment-230315684>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAq8Qt_VLdz30yvRHOYJIr5-0JYFK7H7ks5qSSiagaJpZM4CHfaK>
> .
>


-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by wrighting** [comment]
There is an option to do an almost zero config deploy locally using vagrant (with VirtualBox)
In the scripts directory there are various -vm-install.sh scripts e.g. linux-vm-install.sh

These should install all the dependencies and then create a VM running panoptes with shared folders to the local machine into which you can put your data.
(These scripts can be run directly and don't need to be run from within the panoptes clone - they are a wrapper around the panoptes-boxes project and therefore use the same build process as for the EC2 servers)

Caveats - I think these should work but haven't run/tested for a while and could do with some proper docs - panoptes-boxes has some docs but the scripts attempt to take a lot of that complexity away.
Depending on the size of your data it might be necessary to tweak the setup to allow more space for the VM.

I do have it in mind to investigate Docker rather than a full VM - it should be(!) fairly straightforward to use the Packer Docker builder

**Comment by alimanfoo** [comment]
Thanks Ian. FWIW a docker image would be nice, could just pull and run.

On Tue, Jul 5, 2016 at 10:12 AM, wrighting <notifications@github.com> wrote:

> There is an option to do an almost zero config deploy locally using
> vagrant (with VirtualBox)
> In the scripts directory there are various -vm-install.sh scripts e.g.
> linux-vm-install.sh
>
> These should install all the dependencies and then create a VM running
> panoptes with shared folders to the local machine into which you can put
> your data.
> (These scripts can be run directly and don't need to be run from within
> the panoptes clone - they are a wrapper around the panoptes-boxes project
> and therefore use the same build process as for the EC2 servers)
>
> Caveats - I think these should work but haven't run/tested for a while and
> could do with some proper docs - panoptes-boxes has some docs but the
> scripts attempt to take a lot of that complexity away.
> Depending on the size of your data it might be necessary to tweak the
> setup to allow more space for the VM.
>
> I do have it in mind to investigate Docker rather than a full VM - it
> should be(!) fairly straightforward to use the Packer Docker builder
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cggh/panoptes/issues/156#issuecomment-230426909>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAq8QnBhlOgTyXntolhFnMFv01fbasVbks5qSiAUgaJpZM4CHfaK>
> .
>



-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com <alimanfoo@gmail.com>
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by leehart** [comment]
#64 SQLite option

**Comment by benjeffery** [comment]
Interestingly monetdb has a lite option that embeds the database in python. I've experimented with it but it was at an early stage: https://www.monetdb.org/pipermail/users-list/2015-October/008572.html
My only concern with these DBs is how well they play with concurrent requests to multiple python processes when the app is run via e.g. apache.

**Comment by benjeffery** [comment]
We settled on MonetDB!
