### ISSUE TITLE
Use cases for 2D array sub-selection

### ISSUE THREAD

**Issue by alimanfoo** [cggh/panoptes#28]
This is just an attempt to briefly capture a couple of canonical use cases for sub-selection of 2-dimensional arrays. The focus here is on sub-selection along the longest axis of the array, assuming that the array has one axis which is much longer than the other. This is typically the case for genotype data, where one axis is indexed by variants (may be millions) and the other axis is indexed by samples (usually not more than thousands).

Use Case 1 - Viewing genotypes within a genome region. Here the user has a genome region of interest, e.g., a gene, and a set of samples of interest. The user initially wants to view genotypes for all variants within the region, to get a sense of what the raw data look like. The user then uses a query to filter the variants, to view genotypes at variants which are less likely to be errors or artefacts, e.g., selecting biallelic SNPs which pass the GATK recommended hard filtering rules (is_snp & (num_alleles == 2) & (QD >= 2) & (FS <= 60) & (MQ >= 40) & (HaplotypeScore <= 13) & (MQRankSum >= -12.5) & (ReadPosRankSum >= -8)).

Use Case 2 - Viewing genotypes for selected variants spanning multiple chromosomes. Here the user has a relatively small set of variants of interest which may span multiple chromosomes. A concrete example might be a set of SNPs which are known to be diagnostic of differentiating between the M and S molecular forms in Anopheles gambiae. Another example might be a set of high frequency SNPs which are diagnostic of founder populations of Plasmodium falciparum. The user wants to view genotypes for samples for only these selected variants.

**Comment by benjeffery** [comment]
We've done enough of this to close this one.
