### ISSUE TITLE
Check mobile compatibility and warn if too small screen

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#379]

**Comment by leehart** [comment]
Screen width limit and warning added by PR #437

**Comment by leehart** [comment]
Doesn't work (out-of-the-box) on an iPad or iPhone (Safari browser). Only see the Panoptes logo, not spinning.

**Comment by leehart** [comment]
Perhaps the display could stop squishing when it's beneath the threshold width, and provide scrollbars, instead of showing nothing except the warning.
