### ISSUE TITLE
Give meaningful error if user tries to download unfeasibly large data

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#391]

**Comment by leehart** [comment]
Partly addressed by PR #425.
More to do, pending design.

**Comment by leehart** [comment]
Mostly addressed by PR #432.
I suspect there might be a more satisfactory approach.

**Comment by leehart** [comment]
Ag1000G demo box breaks on 410000 data points.

**Comment by leehart** [comment]
The server-side truncation needs to be taken into account, in both the data points calculation (for download control) and the data table pagination.

**Comment by leehart** [comment]
Related: PR #459
