### ISSUE TITLE
When all values are NULL for a PieChartMap the circles are not drawn

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#402]
E.G. http://176.34.171.251/aa2f0768-1e8d-11e6-9dad-22000a4b0fdc

**Comment by leehart** [comment]
E.g. http://176.34.171.251/
1. Open the Variants table view.
2. Click on a variant's Id in the table; a popup with tabs should appear.
3. Select the "Frequencies Map" tab.
See that there are dashed-lines marking the origins and centers of the pie-charts, but no pie-charts.

**Comment by leehart** [comment]
Pie charts still don't have circles on the Ag1000G demo box.

**Comment by leehart** [comment]
#430
