### ISSUE TITLE
Dataset Manager failing on Ag1000G demo box

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#417]
database=datasetindex&tbname=calculations does not exist on the Ag1000G demo box.
The table "calculations" exists in the "panoptes" db instead.
Maybe different db setup on that box compared to other dev instances?

**Comment by idwright** [comment]
The Ag1000G demo box is a clone of the live box, which was built from the AMI, which was built using the panoptes-boxes scripts - also see scripts/linux-vm-install.sh - so should be standard.
(I don't know what was done when installing the new version)

**Comment by leehart** [comment]
The database containing the calculations table is named "panoptes" on the Ag1000G demo box, but it was assumed to be named "datasetindex", hence the error.

**Comment by benjeffery** [comment]
The database name is set in config.py
