### ISSUE TITLE
Datatable calculations

### ISSUE THREAD

**Issue by pvaut** [cggh/panoptes#42]
Optionally perform some basic SQL calculations on datatables during import.
#### Insert child relation count in parent table records

Using an SQL query along the lines:
update studies a left join (select count(*) as cnt,StudyId from samples group by StudyId) b on a.ID=b.StudyId set a.samplecount=b.cnt;
Optional: similar for other stats, such as average,min,max, ...
#### Pivot tables

Denormalise a view

**Comment by benjeffery** [comment]
We can now do these sort of calculations at runtime.
