### ISSUE TITLE
Pressing enter after specifying name for stored filter should store the query, rather than closing the modal.

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#438]

**Comment by leehart** [comment]
The event is currently handled by QueryPicker's handleEnter(), via Modal's handleHotkey(e).

**Comment by leehart** [comment]
TextField can have an onKeyDown (onEnterKeyDown is deprecated), to check for the Enter keycode.

**Comment by benjeffery** [comment]
Yeah - seen this in a few places. We could consider something like https://github.com/Chrisui/react-hotkeys that bubbles key events based on focus.
