### ISSUE TITLE
Console warnings about unknown props

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#439]
https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by leehart** [comment]
Affects
+ button in EnhancedButton, and div in Tooltip, span in FontIcon, in material-ui/IconButton in StoredTableQueries
+ div in TabbedArea
+ div in TabPane
+ div in Paper, button in EnhancedButton, in PopupButton
+ span in EnhancedButton in ListItem
+ span in QueryString
+ span in PropertyHeader
+ div in CircleRipple (?)
+ div in Modal

**Comment by benjeffery** [comment]
Should be mainly fixed by mui release, but keep this to check.

**Comment by benjeffery** [comment]
Bring some of this forward in #393 as the changes are pervasive and hard to maintain in parallel.

**Comment by benjeffery** [comment]
All fixed except highlighter which is waiting on upstream: https://github.com/helior/react-highlighter/pull/30

**Comment by helior** [comment]
react-highlighter@v0.3.3 published — Have a great weekend everyone!
