### ISSUE TITLE
User editable properties in workspace

### ISSUE THREAD

**Issue by pvaut** [cggh/panoptes#46]
In the workspace definition, allow the creation of datatable properties that can be modified by the user. During a session, the user can then modify these fields in a number of ways:
* Upload a data file (this will then replace the current session-based workspace data upload)
* Store the current selection in a boolean editable field
* Set to a fixed value for all items in the current query / selection
* Simple SQL manipulations, such as copying properties from child relation items

**Comment by benjeffery** [comment]
We don't have workspaces any more, so closing this. I'm not closed to the idea of user data, but it is far down the road.
