### ISSUE TITLE
mini-histogram visualisation of continuous properties for clustered data items on a map

### ISSUE THREAD

**Issue by alimanfoo** [cggh/panoptes#47]
Add feature to enable plotting of mini-histograms showing the distribution for some continuous property for each cluster of data items on a map.

(Mini-histograms for continuous properties are analogue of pie charts for categorical properties.)

**Comment by leehart** [comment]
Pie charts for co-located markers are already in the pipeline; paving the way for mini-histograms!
Pie charts are also only useful when there is more than one unique value to chart, using different colours. For categorical properties a solution to that case is also in the pipe, which is to use a marker of the relevant colour showing the number of markers in the cluster. The common value itself is given on hover. I'm calling that a "bubble".... or maybe a "balloon".
I'm trying to imagine what the analogue situation for continuous properties would be, and whether it poses a visual problem, and what the solution might be.
If a mini-histogram with uniform values looks silly, then one option might be to use the "bubble" again.
