### ISSUE TITLE
Numeric input component

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#510]
Could be a generic "PropertyInput" component. Use in query picker etc.

**Comment by leehart** [comment]
Samples & Variants
Start > Open a table: Variants > Add filter > Add criterion > Value 2 = 0.24

**Comment by leehart** [comment]
Samples & Variants
Start > Open a table: Variants > Add filter > Add criterion > Variant name = SNP_00002

Query string is Variant name = undefined

Press "USE"

`500 (Server Error)`
