### ISSUE TITLE
Genome Browser has a black background-colour

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#605]
Samples & Variants
Start > Genome Browser

![image](https://cloud.githubusercontent.com/assets/4256466/19693302/e9f3e050-9ad2-11e6-89f3-d5e93985e59d.png)

**Comment by benjeffery** [comment]
Weird, which chrome version?

**Comment by leehart** [comment]
@benjeffery Version 54.0.2840.71 (64-bit)
