### ISSUE TITLE
Genotypes column header should scroll with genotypes.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#625]

**Comment by leehart** [comment]
@benjeffery Checking I understand this issue...

Genotypes Example
Start > Genome Browser > Add Channels > Genotypes > haploid > Add 1 channel
Zoom in until genotypes are visible
Hover over list of Sample ID, and scroll up/down
"Sample ID" header should always remain visible?

**Comment by leehart** [comment]
Testing shields...
<img valign="middle" src="https://img.shields.io/badge/Panoptes-l33t-blue.svg?style=social&link=http://2.bp.blogspot.com/-KrE5voy7K5s/UkwKQvL-6rI/AAAAAAAAGw8/63cHFzRXGag/s1600/ArgusEyeless.jpg&link=http://www.marvunapp.com/Appendix5/argusolympians2.jpg">

:vulcan_salute:

**Comment by benjeffery** [comment]
Like this from 1.6.2, where the little column hats float over the table.
![screenshot-33](https://cloud.githubusercontent.com/assets/8552/19919835/20d61f0c-a0cd-11e6-84b5-6c23582db375.png)
