### ISSUE TITLE
Plot SVG leaks onto Start tab

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#651]
Samples & Variants
Start > Table Plotter > 
- Table: Variants
- Plot Type: Bar
- Horizontal: Chromosome
- Vertical: Chromosome

Open Start tab
Hover over the same area as the Table Plotter plot, see crosshair mouse pointer

**Comment by benjeffery** [comment]
Fixed with CSS hack for now https://github.com/cggh/panoptes/commit/83b6710c7c5d3ba4b4f2ad5ef33faa08d5267ffb
