### ISSUE TITLE
Links in the Start tab (in document templates) can change the Start tab content

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#686]
Samples & Variants
Start tab
In the text "An external hyperlink and a **link** to documentation" click on the "link" link.

See that the document irrevocably replaces the Start page, which I expect should be unchangeable.

**Comment by benjeffery** [comment]
Been debating this one with @magnusmanske - I don't see this as a problem, expect that the back button seems not to work for the first state transition!

**Comment by leehart** [comment]
I certainly agree that it's not a functionality issue, because we might actually want to be able to replace the Start tab, just like any other doc, and app admins could be warned not to put self-targeted links in any doc templates that should never self-change. In that respect, this "bug" is only bad content authorship!

I suppose there are a couple of minor related concerns here:
1. The potentially bad user experience of something changing that was expected to stick around forever. (I don't think the safety net of  `Right-click > Back` would cut it, personally.) 
2. The potentially misleading architectural concept of an "unclosableTab", which, although it can't be closed, technically, it can be completely changed, having undesirable consequences.

Having said that, this specific issue (#686) would never have been raised (and might mysteriously vanish!) if the example of an internal link did not happen to be on the Start tab.
