### ISSUE TITLE
Pop-ups from buttons can't be dropped after dragging

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#688]
Samples & Variants
Click on the "Plot of Variants" button.
See a pop-up appear.
Drag the pop-up's blue title bar (to move the pop-up).
See that you can't drop the pop-up.

**Comment by benjeffery** [comment]
Same bug as #687

**Comment by leehart** [comment]
Samples & Variants
Click on the "Untitled" button.
See that nothing happens, except:
`deserialiseComponent.js:67 Uncaught TypeError: Cannot read property 'childrenHash' of undefined(…)`

```
        <PopupButton>
            <div>Some <b>config specified</b> content</div>
        </PopupButton>
```
