### ISSUE TITLE
IconButton tooltip quirk

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#692]
Is this actually intended? I took it to be a glitch!

On Ubuntu, in Chrome
Samples & Variants
Start > Genome browser
Press "Save channel set" and provide a name and description for the saved channel set.
Hover the mouse pointer over the trashcan icon for the saved channel set.
See that the "Delete" tooltip drops down and lands beneath the trashcan icon.

Samples & Variants
Start > Variants > Add filter
Press "Store as..." and provide a name for the stored filter.
Hover the mouse pointer over the trashcan icon for the stored filter.
See that the "Delete" tooltip drops down and lands above the trashcan icon.
Hover the mouse pointer over the pin icon for the stored filter.
See that the "Set as default" tooltip drops down and lands above the trashcan icon.

**Comment by benjeffery** [comment]
Glitch from the "visibility" CSS....

**Comment by benjeffery** [comment]
@leehart I believe this to be fixed - can you confirm?
