### ISSUE TITLE
Deleted stored filters still show

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#693]
Samples & Variants
Start > Variants > Add filter > Store as... "foo" > Store
Start > Variants > Add filter > Store as... "bar" > Store
Delete the first stored filter ("foo").
See that the first stored filter ("foo") disappears from the list.
Try to delete the second stored filter ("bar").
See that the second deleted stored filter ("bar") remains in the list.

The stored filter has actually been deleted, as closing the modal and returning to the list of stored filters indicates.

**Comment by benjeffery** [comment]
Deletes are done by index, not key... Same for queries. So race conditions are a problem.

**Comment by leehart** [comment]
To avoid introducing a separate unique identifier per stored query, I propose that we enforce uniqueness of {name, query}, i.e. users will not be allowed to have two identical queries with the same name (but can still have two identical queries with different names, or two different queries with the same name). Sound reasonable?

**Comment by leehart** [comment]
In the example, the StoredTableQueries component isn't re-rendering after the second delete, even though ConfigStore's modifyConfigSuccess() has done its bit.

**Comment by leehart** [comment]
If storedQueries becomes an object, then I gather that implies we will need unique keys for each stored query? It would be natural to key on the name, then that will have the side-effect of requiring unique names for queries, which isn't so bad, I guess.
