### ISSUE TITLE
Incompatibilities with IE 10 and 11 on Windows 8 and 8.1

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#713]
- Microsoft Windows 8.1
    - [ ] Microsoft Internet Explorer v11 (released 2013-10-17) (known to fail, `'Uint8ClampedArray' is undefined`)
  - Microsoft Windows 8
    - [ ] Microsoft Internet Explorer v10 (released 2012-10-26) (known to fail, `'Uint8ClampedArray' is undefined`)

**Comment by leehart** [comment]
Still true (on master, 22 Dec 2016)

**Comment by leehart** [comment]
Some might say "we don't support any browsers that don't support Uint8ClampedArray"
https://github.com/mapbox/mapbox-gl-js/issues/2444

But there might be workarounds:
https://gist.github.com/gengkev/2295355
https://github.com/substack/typedarray

I gather that an *updated* version of IE v11 should be OK, via https://support.microsoft.com/en-us/kb/2929437

If we don't support IE v10, it's worth noting that IE v11 is not available on Windows 8, only Windows 7 and 8.1.

To complicate matters "There are several differences between Internet Explorer 11 on Windows 8.1 and IE11 on Windows 7"
https://msdn.microsoft.com/en-us/library/dn394063(v=vs.85).aspx

Without a polyfill, if we add feature detection to the sniffing, then I think IE v11 should get the green light.
http://caniuse.com/#search=Uint8ClampedArray

Support for Windows 8, and hence IE v10, has also officially ended, over a year ago...
"Windows 8.0 support ended January 12, 2016. To receive continued support, users must upgrade to Windows 8.1."
http://www.allyncs.com/docs/lifecyclesupport.html
https://www.microsoft.com/en-gb/WindowsForBusiness/End-of-IE-support

**Comment by leehart** [comment]
IE v11 is compatible (on Windows 8 and 8.1) when properly updated (security patched, KB2929437).

IE v10 is not compatible, and is below our minimum support threshold.

**Comment by leehart** [comment]
To investigate workarounds for increased compatibility.

**Comment by benjeffery** [comment]
I've fixed a few IE11 issues. I think we can leave IE10 to rot...
