### ISSUE TITLE
NumericSummaryTrack zoomed in view interaction

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#720]
When hovering, hi-light dots and show tooltip of values.
Click on dot opens DataItemView
https://github.com/malariagen/panoptes-ag1000g/issues/225

**Comment by leehart** [comment]
@benjeffery clicking on a dot isn't opening the DataItemViews on a different PC after #866; maybe be related to previous onClick quirks with same PC (Chrome 55.0.2883.87). Or maybe my mistake.

**Comment by benjeffery** [comment]
I'm wondering if that's an issue with HammerJS. The click handler is done with onTap to prevent panning gestures causing clicks.
