### ISSUE TITLE
UI for sampling

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#735]
Allow the user to enter and control the sampling of a table in the following contexts:

- [x] Non-histogram plots (Histogram plots covered by #734)
- [x] Genotype viewer rows (I don't think columns would make sense)
 
1.6.2 allowed sampling in table views - but I don't really get how that is useful.

**Comment by leehart** [comment]
Hampered by #767 Errors in Genotypes > Genome Browser

**Comment by leehart** [comment]
For posterity: sampling in table views has a bearing on rows pagination, which will need to fetch and show the relevant page of random rows from the full (fixed) set of random rows, where the number of rows has been specified by the user, as per v1.6.2.
