### ISSUE TITLE
Cluster markers on maps sometimes appear cropped

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#779]
Happens on Chrome, after zooming in, or after re-sizing / re-docking the browser window

Affects bubbles and pie-charts.

Ag1000G_Selection
Map Composer > {Markers: Samples; Marker colour: Population}
Zoom in and see that pie-charts and bubbles are cropped to squares

Refresh the page, see that the problem disappears, i.e. cluster markers are no longer cropped and zooming in and out does not (always) trigger the glitch.

Map Composer > {Marker colour: Country}
See that the cropping glitch reappears.

**Comment by leehart** [comment]
This glitch is still evident when:
On Chrome
Ag1000G_Selection > Start

See the flat sides of some of the cluster markers in the embedded map, which does not disappear after refresh.

Does not appear to be affected by zooming or window resizing.
Does not happen on Firefox.

**Comment by benjeffery** [comment]
I haven't seen this in a while....

**Comment by leehart** [comment]
Ag1000G_Selection doesn't have a map on its Start page for me to check....

**Comment by leehart** [comment]
If it is happening, it's very subtle or difficult to reproduce.
