### ISSUE TITLE
Make CAS post-login redirect dynamic.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#828]
Currently it drops you back to the fixed URL in the CAS config

**Comment by idwright** [comment]
This is a separate module - https://github.com/wrighting/cas_wsgi_middleware - available at https://pypi.python.org/pypi/CASWSGIMiddleware/1.2.0

**Comment by benjeffery** [comment]
Hi Ian, yeah I have no idea where to start with this.
Currently if you visit https://www.malariagen.net/panoptes/Pf60 or https://www.malariagen.net/panoptes/Ag1000G_Selection when logged out, then log in, you get sent to the effective_url which is https://www.malariagen.net/panoptes ideally it would sent you back to the original URL.

**Comment by idwright** [comment]
I'd probably start by trying version 1.1.0 from pypi - IIRC 1.2.0 is for python 3

**Comment by benjeffery** [comment]
Ok, we're using a bundled version. That will need replacing first.

**Comment by benjeffery** [comment]
I've used the module version on https://github.com/cggh/panoptes/tree/828 
I don't see how I can use the `gateway_redirect` to achieve this.
I basically need the middleware to add on any CAS username that is logged in, but not to care if one isn't.

**Comment by idwright** [comment]
If the url matches the regex in gateway_redirect, then the gateway param will be added to the call to CAS.
If the gateway param is set then it will do what you describe
