### ISSUE TITLE
Map cluster markers eventually obscure single markers

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#859]
Samples_and_Variants > Map Composer
Markers: Sampling sites

See how the cluster marker with `2` inside it (which is ridiculously large, btw), starts off below the single markers (cluster marker z-index < single markers z-index) but over time (presumably via `GeoLayouter`) obscures the single markers (cluster marker z-index > single markers z-index).

**Comment by leehart** [comment]
The z-index of the `<div class="leaflet-marker-icon [...]` is incrementing as it moves, negating the relative `zIndexOffset` settings.

**Comment by leehart** [comment]
An alternative approach that would avoid (rather than fix) this issue would be to place different kinds of markers (static pins, dynamic clusters, etc.) on entirely different layers.

If we went down that path, I think we could hide that substructure from users and hard-set the layer order, rather than show separate layers in the map control. Btw, there doesn't seem to be an oven-ready way of allowing users to alter the order (or opacity) of map layers, only switch them off and off, but we could develop that if needs be.

**Comment by leehart** [comment]
The Leaflet doc for `zIndexOffset` says `By default, zIndex for the marker image is set automatically based on its latitude.`, which explains what I'm seeing, i.e. zIndex = offset +/- position.

One workaround might be to subtract the marker's y-position from the offset every time it moves, but that seems so dirty!
http://gis.stackexchange.com/questions/115839/custom-ordering-z-index-of-icons-in-leaflet-layer

**Comment by benjeffery** [comment]
For the problem in this issue, why are single points and clusters in separate layers?

**Comment by leehart** [comment]
Technically they are in different FeatureGroups rather than Layers. I imagine that the original reasoning was to logically separate them, e.g. GeoLayouter is only applied to clusters. It might be possible to put them all into the same one FeatureGroup... Do you wonder if that will solve the zIndex issue?

**Comment by benjeffery** [comment]
It's not that I think that the z-index would be solved, just that maybe they should go through the layouter. Even if they aren't moved then the layouter should avoid them.

**Comment by leehart** [comment]
It would be nice to have an "uncluster" option/feature too. (When single points are also controlled by GeoLayouter.)
