### ISSUE TITLE
Padding on `.template-container` causes scroll bars

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#864]

**Comment by leehart** [comment]
Example:
Ag1000G_Selection > Populations
See that there are unnecessary scrollbars on the Details tab, which has `class="template-container"`

Notes:
- Template is one of the viewTypes defined in panoptes/DataItemViews.js
- DataItemViews imports components/Template.js
- Template imports panoptes/ItemTemplate.js and styles/template.scss and uses className `template-container` for ItemTemplate
