### ISSUE TITLE
settings file parsing failures for datatable properties (columns)

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#885]
1. Only the last property id in a list is processed, e.g. only `CountryName` is acknowledged in `- id: CountryCode,CountryName` or `CountryCode, CountryName`.
2. Duplicate columns appear in the table when separate sections for the same property id (column) are used.

Examples:

Pf60 > Samples
1. See that there is no `AlfrescoStudyCode_short` column (which also has no `showInTable: false`) 
2. See that the `AlfrescoStudyCode` column is duplicated in the table.

Temporary workarounds:
1. Use separate sections for the settings of each property (column); no lists of ids.
2. Use only one section for the setting of each property (column); group all settings in one section per id.

**Comment by benjeffery** [comment]
Confirmed. I don't think anything has changed in this code... will look into it

**Comment by benjeffery** [comment]
We actually have a passing unit test for this functionality....

**Comment by idwright** [comment]
Of course you could try using standard YAML syntax instead of creating your own extension....
