### ISSUE TITLE
CustomButton created tab has no name or icon

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#888]
Due to `Content` wrapper being passed on

**Comment by leehart** [comment]
After PR #895 and dataset reimport

Samples_and_Variants > Start
Click on the CustomButton with the Anchor `Click here for the same thing` and see that a tab opens with no name or icon (but the correct content).

How is the tab name and icon supposed to be derived? (Is there a working example of correct behaviour?)

**Comment by benjeffery** [comment]
That behaviour is correct as the code for that example just has a plain `<div>`.

**Comment by leehart** [comment]
Verified that a CustomButton containing a component that has an icon and title results in a tab with an icon and title, e.g.

Pf60 > Start
Click on the CustomButton specified in index.html as:
```
<CustomButton target="tab">
<Anchor><a>samples</a></Anchor>
<Content><DataTableWithActions table="samples"/></Content>
</CustomButton>
```
See that the created tab has an icon and title (from DataTableWithActions).

However, we are now looking at whether the previous example ought to result in a default icon and title, and what the mechanism might be for specifying any arbitrary icon or title.

**Comment by benjeffery** [comment]
I added https://github.com/cggh/panoptes/issues/899 as it is a separate, low-priority issue.
