### ISSUE TITLE
Channel group switching throws an error

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#893]
NumericalTrackGroupChannel does not initialise a list

**Comment by leehart** [comment]
Is this related to the `Uncaught (in promise)` errors I'm seeing?

Samples_and_Variants > Genome Browser
Add channels > Variants > int8 > Add 1 channel

**Comment by benjeffery** [comment]
I don't think so

**Comment by leehart** [comment]
Fixed by PR #895
