### ISSUE TITLE
`showInTable` should be used to filter properties in dropdowns

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#897]

**Comment by leehart** [comment]
Samples_and_Variants > Variants
See that the Position column is shown (OK)
Samples_and_Variants > Dataset Manager > Edit Variants
Set the position property (column) to `showInTable: false`
Samples_and_Variants > Variants
See that the Position column is not shown (OK)
Add Filter > Add Criterion
See that the Position column is shown (as an option in the drop-down)
