### ISSUE TITLE
Add colours to Pivot Table percentages

### ISSUE THREAD

**Issue by leehart** [cggh/panoptes#909]
Samples_and_Variants > Variants
See that the "Value 1" and "Value 2" columns use colour to help convey their values.

Samples_and_Variants > Variants > Pivot Table
{Column: Chromosome, Row: High Quality, Display: Percentage of total}
See that the percentage values are shown simply as black text on a white background.

Add colour to the Pivot Table to help convey percentage values.

**Comment by benjeffery** [comment]
After the merge I removed the deepClone with https://github.com/cggh/panoptes/commit/663c6728476c30a6e2d1549f8f23ba4983ce1ad1
