### ISSUE TITLE
Query editor categorical fields

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#920]
Couple problems:

- [x] When choosing "like" or "contains" or "not contains" the drop down is still present so you can't type in anything, should be plain text box.
- [x] Equals column should show drop down of columns, not values

**Comment by leehart** [comment]
I expect "Starts with" should also provide a plain text box.

**Comment by leehart** [comment]
Some column types cannot be directly compared, e.g.

On branch 920 at commit a3fbd26

Samples_and_Variants > Variants > Add filter > Add criterion
Variant name "Equals column" Variant name
Press "Use"
See no error

Press "Clear filter"
Samples_and_Variants > Variants > Add filter > Add criterion
int8 "Equals column" Variant name
Press "Use"
See an error
Server log:
```
@@@###QRY:SELECT "chromosome","position","SnpName","Value1","Value2","Value_three","Extra_1","NRAF_WAF","NRAF_EAF","NRAF_SAF","int8","int16","int32","boolean" FROM "variants" WHERE ("int8"="SnpName") LIMIT 301 OFFSET 0
[...]
OperationalError: 22018!conversion of string 'SNP_00001' to type bte failed.
```

Interestingly it does not trigger a type conversion error when the equality is the other way around, e.g.:
Variant name "Equals column" int8
```
@@@###QRY:SELECT "chromosome","position","SnpName","Value1","Value2","Value_three","Extra_1","NRAF_WAF","NRAF_EAF","NRAF_SAF","int8","int16","int32","boolean" FROM "variants" WHERE ("SnpName"="int8") LIMIT 301 OFFSET 0
```
