### ISSUE TITLE
Sorting in pivots doesn't respect display mode

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#941]

**Comment by leehart** [comment]
Samples_and_Variants > Variants > Pivot Table
Pivot variants > {Column: Chromosome; Row: Position; Display: Percentage of total}
See that the values are still shown as counts (Issue #942)
Sort the Pf3D7_01_v3 column descending. See that 88% is at the top (OK).
Sort the 10 row descending. See that 8% is on the left (OK).

Samples_and_Variants > Variants > Pivot Table
Pivot variants > {Column: Chromosome; Row: Position; Display: Percentage of column total}
See that the values are still shown as counts (Issue #942)
Sort the Pf3D7_01_v3 column descending. See that 100% is at the top (OK).
Sort the 10 row descending. See that 8% is on the left. (Should be 33%.)
