### ISSUE TITLE
Pivot table default sort should be alphanumeric

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#944]

**Comment by leehart** [comment]
I can't seem to find the problem, or can't see what you mean.

**Comment by leehart** [comment]
Samples_and_Variants > Samples > Pivot Table
Pivot samples > {Column: Sample key; Row: Value 1; Display Counts}
See that there is no sort order for the Value 1 rows.
Pivot samples > {Column: SampleDate; Row: Value 1; Display Counts}
See that there is no sort order for the Value 2 rows.
