### ISSUE TITLE
Table Download omitting data.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#947]
eg. https://www.malariagen.net/panoptes/Pf60_Internal/fd5632b2-5a65-11e7-9b8c-42010a840002
Click download and only get the first few thousand rows.

**Comment by leehart** [comment]
Geographic > Samples
See there are 10000 samples
Press "Download Data"
See there are 10000 samples in the downloaded data. (OK.)

Pf60_Internal > Samples
See there are 7182 samples
Press "Download Data"
See the warning "You have asked to download 165186 data points, which is more than our current limit of 100000. Please use a stricter filter or fewer columns, or contact us directly." (OK.)

Pf60_Internal > Samples
Add Filter: {Year contains "201"}
Press "Use"
See there are 5222 samples
Press "Download Data"
See there are 2858 samples. (Bug.)

**Comment by leehart** [comment]
Note: due to problematic characters in year column.

**Comment by leehart** [comment]
Pf60_Internal is now experiencing other download problems... :-(

**Comment by leehart** [comment]
Fixed (production was a commit behind)
