### ISSUE TITLE
Add a map layer for rendering GeoJSON.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#955]
After #954
See http://leafletjs.com/examples/geojson/ and https://jsfiddle.net/e3zh51fp/7/
It will be a very simple wrapper, mostly to get the `propTypes` for template conversion.

Something like 
`<GeoJSON json='{"type": "Feature", "geometry": { "type": "Polygon", "coordinates": [[[-10.....]]]}}' colour="#FF00FF" weight="5" opacity="0.6" />`

**Comment by leehart** [comment]
Closed by PR #961
