### ISSUE TITLE
Make colour allocator recognise colour values.

### ISSUE THREAD

**Issue by benjeffery** [cggh/panoptes#957]
In `Colours.js/propertyColour`

If `propConfig.isText` and `value` is one of the HTML colour forms `#HHHHHH` `rgb(NUM,NUM,NUM)` or `rgba(NUM, NUM, NUM, NUM)` then return `value` otherwise fall back to current behaviour.

Note this should happen whatever the value of `isCategorical`

**Comment by benjeffery** [comment]
This may be helpful:
https://gist.github.com/olmokramer/82ccce673f86db7cda5e

**Comment by benjeffery** [comment]
At line 37 instead of returning the d3 function directly, call it from a function that checks the regex and only calls the d3 function if it doesn't match.

**Comment by leehart** [comment]
Closed by PR #961
